# Generated by Django 5.2.5 on 2025-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='companies.company'),
        ),
    ]
